//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHAD.DesktopApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHAD.DesktopApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        public static string Agriculture {
            get {
                return ResourceManager.GetString("Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CHAD (Climate, Hydrology, Agriculture, &amp; Decision-making) model simulates interactions among some of the basic climatic, aquatic, agricultural, and decision-making processes impacting operations of farms..
        /// </summary>
        public static string ChadInfoText {
            get {
                return ResourceManager.GetString("ChadInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAD Model.
        /// </summary>
        public static string ChadModel {
            get {
                return ResourceManager.GetString("ChadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose below from an existing simulation configuration or create a new one..
        /// </summary>
        public static string ChooseSimulationText {
            get {
                return ResourceManager.GetString("ChooseSimulationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climate.
        /// </summary>
        public static string Climate {
            get {
                return ResourceManager.GetString("Climate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClimateChangePrecipMean.
        /// </summary>
        public static string ClimateChangePrecipMean {
            get {
                return ResourceManager.GetString("ClimateChangePrecipMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClimateChangePrecipSD.
        /// </summary>
        public static string ClimateChangePrecipSD {
            get {
                return ResourceManager.GetString("ClimateChangePrecipSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClimateChangeTempMean.
        /// </summary>
        public static string ClimateChangeTempMean {
            get {
                return ResourceManager.GetString("ClimateChangeTempMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClimateChangeTempSD.
        /// </summary>
        public static string ClimateChangeTempSD {
            get {
                return ResourceManager.GetString("ClimateChangeTempSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputClimate.xlsx is invalid..
        /// </summary>
        public static string ClimateFileInvalid {
            get {
                return ResourceManager.GetString("ClimateFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name.
        /// </summary>
        public static string ConfigurationName {
            get {
                return ResourceManager.GetString("ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostAlfalfa.
        /// </summary>
        public static string CostAlfalfa {
            get {
                return ResourceManager.GetString("CostAlfalfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostBarley.
        /// </summary>
        public static string CostBarley {
            get {
                return ResourceManager.GetString("CostBarley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CostWheat.
        /// </summary>
        public static string CostWheat {
            get {
                return ResourceManager.GetString("CostWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputCropEvapTrans.xlsx is invalid..
        /// </summary>
        public static string CropEvapTransFileInvalid {
            get {
                return ResourceManager.GetString("CropEvapTransFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current day.
        /// </summary>
        public static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current simulation.
        /// </summary>
        public static string CurrentSimulation {
            get {
                return ResourceManager.GetString("CurrentSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision-making.
        /// </summary>
        public static string DecisionMaking {
            get {
                return ResourceManager.GetString("DecisionMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique name for this configuration.
        /// </summary>
        public static string EditSimulationInfoText {
            get {
                return ResourceManager.GetString("EditSimulationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputFieldSize.xlsx is invalid..
        /// </summary>
        public static string FieldsFileInvalid {
            get {
                return ResourceManager.GetString("FieldsFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputFinancials.xlsx is invalid..
        /// </summary>
        public static string FinancialsFileInvalid {
            get {
                return ResourceManager.GetString("FinancialsFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrology.
        /// </summary>
        public static string Hydrology {
            get {
                return ResourceManager.GetString("Hydrology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeakAquiferFrac.
        /// </summary>
        public static string LeakAquiferFrac {
            get {
                return ResourceManager.GetString("LeakAquiferFrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeanBushelsAlfalfaPerAcre.
        /// </summary>
        public static string MeanBushelsAlfalfaPerAcre {
            get {
                return ResourceManager.GetString("MeanBushelsAlfalfaPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeanBushelsBarleyPerAcre.
        /// </summary>
        public static string MeanBushelsBarleyPerAcre {
            get {
                return ResourceManager.GetString("MeanBushelsBarleyPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeanBushelsWheatPerAcre.
        /// </summary>
        public static string MeanBushelsWheatPerAcre {
            get {
                return ResourceManager.GetString("MeanBushelsWheatPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeltingPoint.
        /// </summary>
        public static string MeltingPoint {
            get {
                return ResourceManager.GetString("MeltingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeltingRate.
        /// </summary>
        public static string MeltingRate {
            get {
                return ResourceManager.GetString("MeltingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number os seasons:.
        /// </summary>
        public static string NumberOfSeasons {
            get {
                return ResourceManager.GetString("NumberOfSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of simulations:.
        /// </summary>
        public static string NumberOfSimulations {
            get {
                return ResourceManager.GetString("NumberOfSimulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PercFromFieldFrac.
        /// </summary>
        public static string PercFromFieldFrac {
            get {
                return ResourceManager.GetString("PercFromFieldFrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt; Previous.
        /// </summary>
        public static string PreviousButtonText {
            get {
                return ResourceManager.GetString("PreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfitCRP.
        /// </summary>
        public static string ProfitCRP {
            get {
                return ResourceManager.GetString("ProfitCRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of season is greater than InputFinancials.xlsx contains..
        /// </summary>
        public static string SeasonNumberInvalid {
            get {
                return ResourceManager.GetString("SeasonNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select configuration:.
        /// </summary>
        public static string SelectConfiguration {
            get {
                return ResourceManager.GetString("SelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOSIEL.
        /// </summary>
        public static string SOSIEL {
            get {
                return ResourceManager.GetString("SOSIEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SustainableLevelAquifer.
        /// </summary>
        public static string SustainableLevelAquifer {
            get {
                return ResourceManager.GetString("SustainableLevelAquifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CHAD Model.
        /// </summary>
        public static string TheChadModel {
            get {
                return ResourceManager.GetString("TheChadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time since start.
        /// </summary>
        public static string TimeSinceStart {
            get {
                return ResourceManager.GetString("TimeSinceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterCurtailmentBase.
        /// </summary>
        public static string WaterCurtailmentBase {
            get {
                return ResourceManager.GetString("WaterCurtailmentBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterCurtailmentRate.
        /// </summary>
        public static string WaterCurtailmentRate {
            get {
                return ResourceManager.GetString("WaterCurtailmentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterInAquifer.
        /// </summary>
        public static string WaterInAquifer {
            get {
                return ResourceManager.GetString("WaterInAquifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterInAquiferMax.
        /// </summary>
        public static string WaterInAquiferMax {
            get {
                return ResourceManager.GetString("WaterInAquiferMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterInSnowpack.
        /// </summary>
        public static string WaterInSnowpack {
            get {
                return ResourceManager.GetString("WaterInSnowpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterStorFieldCap.
        /// </summary>
        public static string WaterStorFieldCap {
            get {
                return ResourceManager.GetString("WaterStorFieldCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterUsageMax.
        /// </summary>
        public static string WaterUsageMax {
            get {
                return ResourceManager.GetString("WaterUsageMax", resourceCulture);
            }
        }
    }
}
