//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture.
        /// </summary>
        public static string Agriculture {
            get {
                return ResourceManager.GetString("Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CHAD (Climate, Hydrology, Agriculture, &amp; Decision-making) model simulates interactions among some of the basic climatic, aquatic, agricultural, and decision-making processes impacting operations of farms..
        /// </summary>
        public static string ChadInfoText {
            get {
                return ResourceManager.GetString("ChadInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAD Model.
        /// </summary>
        public static string ChadModel {
            get {
                return ResourceManager.GetString("ChadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose below from an existing simulation configuration or create a new one..
        /// </summary>
        public static string ChooseSimulationText {
            get {
                return ResourceManager.GetString("ChooseSimulationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name.
        /// </summary>
        public static string ConfigurationName {
            get {
                return ResourceManager.GetString("ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current day.
        /// </summary>
        public static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current simulation.
        /// </summary>
        public static string CurrentSimulation {
            get {
                return ResourceManager.GetString("CurrentSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision-making.
        /// </summary>
        public static string DecisionMaking {
            get {
                return ResourceManager.GetString("DecisionMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique name for this configuration.
        /// </summary>
        public static string EditSimulationInfoText {
            get {
                return ResourceManager.GetString("EditSimulationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrology.
        /// </summary>
        public static string Hydrology {
            get {
                return ResourceManager.GetString("Hydrology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of simulations:.
        /// </summary>
        public static string NumberOfSimulations {
            get {
                return ResourceManager.GetString("NumberOfSimulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt; Previous.
        /// </summary>
        public static string PreviousButtonText {
            get {
                return ResourceManager.GetString("PreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select configuration:.
        /// </summary>
        public static string SelectConfiguration {
            get {
                return ResourceManager.GetString("SelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOSIEL.
        /// </summary>
        public static string Sosiel {
            get {
                return ResourceManager.GetString("Sosiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CHAD Model.
        /// </summary>
        public static string TheChadModel {
            get {
                return ResourceManager.GetString("TheChadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time since start.
        /// </summary>
        public static string TimeSinceStart {
            get {
                return ResourceManager.GetString("TimeSinceStart", resourceCulture);
            }
        }
    }
}
