//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHAD.DesktopApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CHAD.DesktopApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Agriculture.
        /// </summary>
        public static string Agriculture {
            get {
                return ResourceManager.GetString("Agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Beta.
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The CHAD (Climate, Hydrology, Agriculture, &amp; Decision-making) model simulates interactions among some of the basic climatic, aquatic, agricultural, and decision-making processes impacting operations of farms..
        /// </summary>
        public static string ChadInfoText {
            get {
                return ResourceManager.GetString("ChadInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CHAD Model.
        /// </summary>
        public static string ChadModel {
            get {
                return ResourceManager.GetString("ChadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose below from an existing simulation configuration or create a new one..
        /// </summary>
        public static string ChooseSimulationText {
            get {
                return ResourceManager.GetString("ChooseSimulationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Climate.
        /// </summary>
        public static string Climate {
            get {
                return ResourceManager.GetString("Climate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClimateChangePrecipMean.
        /// </summary>
        public static string ClimateChangePrecipMean {
            get {
                return ResourceManager.GetString("ClimateChangePrecipMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClimateChangePrecipSD.
        /// </summary>
        public static string ClimateChangePrecipSD {
            get {
                return ResourceManager.GetString("ClimateChangePrecipSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClimateChangeTempMean.
        /// </summary>
        public static string ClimateChangeTempMean {
            get {
                return ResourceManager.GetString("ClimateChangeTempMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ClimateChangeTempSD.
        /// </summary>
        public static string ClimateChangeTempSD {
            get {
                return ResourceManager.GetString("ClimateChangeTempSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of days is greater than InputClimate.xlsx contains..
        /// </summary>
        public static string ClimateDaysNumberInvalid {
            get {
                return ResourceManager.GetString("ClimateDaysNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputClimate.xlsx is invalid..
        /// </summary>
        public static string ClimateFileInvalid {
            get {
                return ResourceManager.GetString("ClimateFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration name.
        /// </summary>
        public static string ConfigurationName {
            get {
                return ResourceManager.GetString("ConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CostAlfalfa.
        /// </summary>
        public static string CostAlfalfa {
            get {
                return ResourceManager.GetString("CostAlfalfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CostBarley.
        /// </summary>
        public static string CostBarley {
            get {
                return ResourceManager.GetString("CostBarley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CostWheat.
        /// </summary>
        public static string CostWheat {
            get {
                return ResourceManager.GetString("CostWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of days is greater than InputCropEvapTrans.xlsx contains..
        /// </summary>
        public static string CropEvapTransDaysNumberInvalid {
            get {
                return ResourceManager.GetString("CropEvapTransDaysNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputCropEvapTrans.xlsx is invalid..
        /// </summary>
        public static string CropEvapTransFileInvalid {
            get {
                return ResourceManager.GetString("CropEvapTransFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current day.
        /// </summary>
        public static string CurrentDay {
            get {
                return ResourceManager.GetString("CurrentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current season.
        /// </summary>
        public static string CurrentSeason {
            get {
                return ResourceManager.GetString("CurrentSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current simulation.
        /// </summary>
        public static string CurrentSimulation {
            get {
                return ResourceManager.GetString("CurrentSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decision-making.
        /// </summary>
        public static string DecisionMaking {
            get {
                return ResourceManager.GetString("DecisionMaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputDrought.xlsx is invalid..
        /// </summary>
        public static string DroughtFileInvalid {
            get {
                return ResourceManager.GetString("DroughtFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of season is greater than InputDrought.xlsx contains..
        /// </summary>
        public static string DroughtSeasonNumberInvalid {
            get {
                return ResourceManager.GetString("DroughtSeasonNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a unique name for this configuration.
        /// </summary>
        public static string EditSimulationInfoText {
            get {
                return ResourceManager.GetString("EditSimulationInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FieldDepth.
        /// </summary>
        public static string FieldDepth {
            get {
                return ResourceManager.GetString("FieldDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputFieldSize.xlsx is invalid..
        /// </summary>
        public static string FieldsFileInvalid {
            get {
                return ResourceManager.GetString("FieldsFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InputFinancials.xlsx is invalid..
        /// </summary>
        public static string FinancialsFileInvalid {
            get {
                return ResourceManager.GetString("FinancialsFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of season is greater than InputFinancials.xlsx contains..
        /// </summary>
        public static string FinansialsSeasonNumberInvalid {
            get {
                return ResourceManager.GetString("FinansialsSeasonNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hydrology.
        /// </summary>
        public static string Hydrology {
            get {
                return ResourceManager.GetString("Hydrology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LeakAquiferFrac.
        /// </summary>
        public static string LeakAquiferFrac {
            get {
                return ResourceManager.GetString("LeakAquiferFrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeanBushelsAlfalfaPerAcre.
        /// </summary>
        public static string MeanBushelsAlfalfaPerAcre {
            get {
                return ResourceManager.GetString("MeanBushelsAlfalfaPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeanBushelsBarleyPerAcre.
        /// </summary>
        public static string MeanBushelsBarleyPerAcre {
            get {
                return ResourceManager.GetString("MeanBushelsBarleyPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeanBushelsWheatPerAcre.
        /// </summary>
        public static string MeanBushelsWheatPerAcre {
            get {
                return ResourceManager.GetString("MeanBushelsWheatPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeanTonsAlfalfaPerAcre.
        /// </summary>
        public static string MeanTonsAlfalfaPerAcre {
            get {
                return ResourceManager.GetString("MeanTonsAlfalfaPerAcre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeltingPoint.
        /// </summary>
        public static string MeltingPoint {
            get {
                return ResourceManager.GetString("MeltingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MeltingRate.
        /// </summary>
        public static string MeltingRate {
            get {
                return ResourceManager.GetString("MeltingRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next &gt;.
        /// </summary>
        public static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of days.
        /// </summary>
        public static string NumberOfDays {
            get {
                return ResourceManager.GetString("NumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number os seasons:.
        /// </summary>
        public static string NumberOfSeasons {
            get {
                return ResourceManager.GetString("NumberOfSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of simulations:.
        /// </summary>
        public static string NumberOfSimulations {
            get {
                return ResourceManager.GetString("NumberOfSimulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configurable parameters with only one value. Parameters with two or more values are modified in the files in the &quot;Configurations&quot; folder..
        /// </summary>
        public static string ParametersInfo {
            get {
                return ResourceManager.GetString("ParametersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PercFromFieldFrac.
        /// </summary>
        public static string PercFromFieldFrac {
            get {
                return ResourceManager.GetString("PercFromFieldFrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  &lt; Previous.
        /// </summary>
        public static string PreviousButtonText {
            get {
                return ResourceManager.GetString("PreviousButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfitCRP.
        /// </summary>
        public static string ProfitCRP {
            get {
                return ResourceManager.GetString("ProfitCRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select configuration:.
        /// </summary>
        public static string SelectConfiguration {
            get {
                return ResourceManager.GetString("SelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SOSIEL.
        /// </summary>
        public static string SOSIEL {
            get {
                return ResourceManager.GetString("SOSIEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SOSIEL Configuration:.
        /// </summary>
        public static string SOSIELConfiguration {
            get {
                return ResourceManager.GetString("SOSIELConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SustainableLevelAquifer.
        /// </summary>
        public static string SustainableLevelAquifer {
            get {
                return ResourceManager.GetString("SustainableLevelAquifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The CHAD Model.
        /// </summary>
        public static string TheChadModel {
            get {
                return ResourceManager.GetString("TheChadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time since start.
        /// </summary>
        public static string TimeSinceStart {
            get {
                return ResourceManager.GetString("TimeSinceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterInAquifer.
        /// </summary>
        public static string WaterInAquifer {
            get {
                return ResourceManager.GetString("WaterInAquifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterInAquiferMax.
        /// </summary>
        public static string WaterInAquiferMax {
            get {
                return ResourceManager.GetString("WaterInAquiferMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterInSnowpack.
        /// </summary>
        public static string WaterInSnowpack {
            get {
                return ResourceManager.GetString("WaterInSnowpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterStorFieldCap.
        /// </summary>
        public static string WaterStorFieldCap {
            get {
                return ResourceManager.GetString("WaterStorFieldCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterUsageMax.
        /// </summary>
        public static string WaterUsageMax {
            get {
                return ResourceManager.GetString("WaterUsageMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterUseBase.
        /// </summary>
        public static string WaterUseBase {
            get {
                return ResourceManager.GetString("WaterUseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WaterUseRate.
        /// </summary>
        public static string WaterUseRate {
            get {
                return ResourceManager.GetString("WaterUseRate", resourceCulture);
            }
        }
    }
}
